# fly.toml app configuration file generated for ollama-fastapi-railway-deployment-qst2ba on 2026-06-26T07:49:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ollama-fastapi-railway-deployment-qst2ba'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_URL = 'postgresql://neondb_owner:npg_1imPJgOw5qBc@ep-divine-fog-ajro56fz-pooler.c-3.us-east-2.aws.neon.tech/Dailymotion%20?sslmode=require&channel_binding=require'
  OLLAMA_HOST = 'http://localhost:11434'
  OLLAMA_KEEP_ALIVE = '-1'
  OLLAMA_MODELS = '/root/.ollama/models'
  OLLAMA_NOPRUNE = '1'

[processes]
  qwen = '/start.sh'
  tinyllama = '/start.sh'

[[mounts]]
  source = 'ollama_data'
  destination = '/root/.ollama'
  processes = ['qwen', 'tinyllama']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['qwen', 'tinyllama']

  [[http_service.checks]]
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '4096'
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 256
